#!/bin/bash

print_help() {
  echo "Usage: bindiff FILE1 FILE2"
  echo
  echo "Options:"
  echo "    -h, --help      Print usage"
}

bindiff() {
  echo "--- xxd/$1"
  echo "+++ xxd/$2"
  diff -u <(xxd "$1") <(xxd "$2") | tail -n +3
}

case "$1" in
  "" )
    print_help
    exit 1
    ;;

  -h | --help )
    print_help
    ;;

  * )
    bindiff "$@"
    ;;
esac
